### ISSUE TITLE
Update to Node.js 20

### ISSUE THREAD

**Issue by AlexandrNikulin** [charliealbright/appcenter-cli-action#50]
Warning:
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: charliealbright/appcenter-cli-action@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Any plans for it?

**Comment by charliealbright** [comment]
Fixed in [v1.0.2](https://github.com/charliealbright/appcenter-cli-action/releases/tag/v1.0.2). Thanks for the reminder!

`v1` tag has been updated as well so if that's what you reference, you should automatically receive this update.
